### PR TITLE
[CI] FIX folder name 

### PR DESCRIPTION
**Pull request by bakpaul**
Sorry, forgot the S

### CODE REVIEW

**Comment by alxbilger** [comment]
@bakpaul Hi, could you identify the cause of the error here: https://github.com/SofaDefrost/SofaViscoElastic/actions/runs/8722604980 ?

**Comment by bakpaul** [comment]
Yes my IDE did bad things, it has to do with the indent... I'll make a PR

**Comment by bakpaul** [comment]
See : https://github.com/SofaDefrost/SofaViscoElastic/pull/19 
Now the checks are going good. Sorry for the multiples PRs

**Comment by pasqualeferr94** [comment]
Hello @alxbilger and @bakpaul, 
 also, did the #19 go wrong? (Windows not genrated). There are other errors?
failed

**Comment by pasqualeferr94** [comment]
Hello @bakpaul, sorry to disturb you again, but it doesn't compile the Windows project now. Which would be the problem?
failed2

**Pull request merged**
